### ISSUE TITLE
change the text under the field input 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/dlm-cors#2]
**Is your feature request related to a problem? Please describe.**
Specify the requester URL so we can allow cross site download requests comming from the specified source. Add * in order to accept all.

![image](https://user-images.githubusercontent.com/7841556/210780758-d005080e-286a-41f0-a3a0-f9ecb2600579.png)

honestly it is a bit confusing. Can we simplify it so it will be easier to understand what needs to be added and how it needs to look?

**Comment by cristianraiber** [comment]
I think we should also link to our doc entry; here about this: 

As per our example:
- domain A is the domain we're using to serve the downloads 
- domain B is the domain we're using to host the downloads on
- DLM CORS has to be installed on domain B, and we should add domain A in the "requester URL" input field. 


----

Here's my take on this:
- change the label to "CORS URL."
- change the description to: "In the above input box, you should enter the URL of the website on which you wish to serve the downloads. According to our doc, you can consult by clicking on this link; in the input box above, you'd enter Domain A.
